version: '3'

services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/build
    ports:
      - '3001:3001'
