version: '3'
services:
  postgres:
    image: "postgres:9.4"
    restart: always
    env_file:
      - .env
    volumes:
      - ./docker/postgres-data:/var/lib/pgsql/data
    ports:
      - '5432:5432'
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - '6379:6379'
  # ts-node-docker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: base
  #   volumes:
  #     - ./src:/home/node/app/src
  #     - ./nodemon.json:/home/node/app/nodemon.json
  #   container_name: ts-node-docker
  #   expose:
  #     - '3000'
  #   ports:
  #     - '3000:3000'
  #   links:
  #     - postgres
  #     - redis
  #   command: npm run dev
