version: '3'
volumes:
  postgres-data:

services:
  postgres:
    image: "postgres:9.4"
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - '6379:6379'
      
  app:
    restart: "no"
    depends_on:
      - postgres
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
      - '4040:4040'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - /app/node_modules